export type {
  Alert,
  DashboardData,
  Diagnostic,
  ObdSnapshot,
  ObdCapability,
  ObdDtcStatus,
  ObdLivePidValue,
  ObdReadiness,
  Severity,
  SimulatedObdDtc,
  Telemetry,
  TelemetryBatchResponse,
  TelemetryInput,
  SimulatedObdSnapshot,
  SimulationProfile,
  Trip,
  Vehicle,
  VehicleHealth,
  VehicleScenario,
} from '../../../packages/shared-types/src'
