export type {
  Alert,
  DashboardData,
  Diagnostic,
  Severity,
  SimulationScenario,
  SimulationStatus,
  Telemetry,
  TelemetryBatchResponse,
  TelemetryInput,
  Trip,
  Vehicle,
  VehicleHealth,
  VehicleHealthStatus,
  VehicleScenario,
} from '../../../packages/shared-types/src'
