create table vehicles (
    id uuid primary key,
    name varchar(80) not null,
    vin varchar(17) not null unique,
    manufacturer varchar(80) not null,
    model varchar(80) not null,
    model_year integer not null,
    license_plate varchar(10) not null unique,
    odometer_km double precision not null,
    created_at timestamp with time zone not null
);

create table telemetry_samples (
    id bigint generated by default as identity primary key,
    vehicle_id uuid not null references vehicles(id) on delete cascade,
    recorded_at timestamp with time zone not null,
    speed_kph double precision not null,
    rpm integer not null,
    engine_temp_c double precision not null,
    engine_load_percent double precision not null,
    throttle_position_percent double precision not null,
    battery_voltage double precision not null,
    fuel_level_percent double precision not null,
    latitude double precision,
    longitude double precision,
    source varchar(20) not null
);

create table diagnostics (
    id uuid primary key,
    vehicle_id uuid not null references vehicles(id) on delete cascade,
    telemetry_id bigint references telemetry_samples(id) on delete set null,
    code varchar(64) not null,
    description varchar(255) not null,
    severity varchar(16) not null,
    status varchar(16) not null,
    detected_at timestamp with time zone not null,
    resolved_at timestamp with time zone
);

create table alerts (
    id uuid primary key,
    vehicle_id uuid not null references vehicles(id) on delete cascade,
    telemetry_id bigint references telemetry_samples(id) on delete set null,
    type varchar(32) not null,
    severity varchar(16) not null,
    title varchar(120) not null,
    message varchar(255) not null,
    status varchar(20) not null,
    created_at timestamp with time zone not null,
    acknowledged_at timestamp with time zone
);

create index idx_telemetry_vehicle_recorded on telemetry_samples(vehicle_id, recorded_at desc);
create index idx_diagnostic_vehicle_status on diagnostics(vehicle_id, status);
create index idx_alert_vehicle_status on alerts(vehicle_id, status);
